version: "3"

services:
    atom:
        image: fabert/docker-atom
        volumes:
            - /tmp/.X11-unix/:/tmp/.X11-unix/
            - /dev/shm:/dev/shm
        environment:
            - DISPLAY=${DISPLAY}
